<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Outboundcalls_US</name>
   <tag></tag>
   <elementGuidId>a4c65fb5-1e2f-40de-ad37-677a47c5f6f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-inherit.css-1352336</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cx1_agent_root']/div[2]/div[3]/div/div[2]/div/div/div/div/div/div[2]/div/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;cxone-voice-contact&quot;] >> internal:text=&quot;Outboundcalls_US&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>5149aa56-dc1d-4c2f-bc6f-ca602809ead6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-inherit css-1352336</value>
      <webElementGuid>af2773c9-7a6e-49a4-8c1d-0c0b8c1ff7a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outboundcalls_US</value>
      <webElementGuid>d7669049-945c-4bda-87fe-5412c5db75de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@id=&quot;cx1_agent_root&quot;]/main[1]/div[@class=&quot;MuiBox-root css-1uq669f&quot;]/main[@class=&quot;MuiBox-root css-o3ihhy&quot;]/div[@id=&quot;cx1_agent_root&quot;]/div[@class=&quot;MuiBox-root css-19ku4tl&quot;]/div[@class=&quot;MuiGrid-root css-rfnosa&quot;]/div[@class=&quot;MuiBox-root css-j5cgbc&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-elevation1 MuiCard-root css-1jcx4ix&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-wrsvkf&quot;]/div[@class=&quot;css-1dnzb0&quot;]/div[@class=&quot;css-5qe0tw&quot;]/div[@class=&quot;MuiBox-root css-1bm5dgn&quot;]/div[@class=&quot;css-1xdwko8&quot;]/div[@class=&quot;css-ofo63b&quot;]/div[@class=&quot;MuiBox-root css-1xhj18k&quot;]/div[@class=&quot;MuiBox-root css-179ws4o&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-inherit css-1352336&quot;]</value>
      <webElementGuid>a3e92024-aa45-422c-94b2-98c990b80f3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[3]/div/div[2]/div/div/div/div/div/div[2]/div/div/p</value>
      <webElementGuid>d0d3dc97-39ac-4276-a8b2-057b000873cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#'])[1]/following::p[2]</value>
      <webElementGuid>892bcd55-a3a2-4343-9ea6-070b8ecb1311</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='+'])[1]/following::p[2]</value>
      <webElementGuid>fb02f657-6c68-457a-b3a8-907eafdea2ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Outboundcalls_US'])[2]/preceding::p[1]</value>
      <webElementGuid>32854d15-8dc9-4faf-b24c-f09c93ed0f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outboundcalls_US']/parent::*</value>
      <webElementGuid>93d87dc2-2b28-4b36-bbaa-af396e7f4c01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/p</value>
      <webElementGuid>c9e3a07f-c3ee-405d-8f00-f8d527299446</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Outboundcalls_US' or . = 'Outboundcalls_US')]</value>
      <webElementGuid>ad72be93-e153-4019-8eb4-c8d5e5f681f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[3]/div/div/div/div/div/div/div/div[2]/div/div/p</value>
      <webElementGuid>2ee1df64-750f-457d-bb21-e2380e94e252</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dialed number is invalid'])[1]/following::p[3]</value>
      <webElementGuid>416c9643-5937-4f1b-ab45-ab92e39222e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
