<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_abc</name>
   <tag></tag>
   <elementGuidId>1e480443-5389-445e-91e0-c0166479234b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cx1_agent_root']/div[2]/div[3]/div/div/div/div[3]/button[2]/span[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.dialKeyText.MuiBox-root.css-t1f1ul</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;dial-button-1&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b7319655-8409-4e6e-827d-b63875dfee7a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dialKeyText MuiBox-root css-t1f1ul</value>
      <webElementGuid>62f3f538-fa0e-4778-8668-8910167b4bf3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>abc</value>
      <webElementGuid>7b94ab8b-332e-4ee8-b944-2325d6046e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@id=&quot;cx1_agent_root&quot;]/main[1]/div[@class=&quot;MuiBox-root css-1uq669f&quot;]/main[@class=&quot;MuiBox-root css-o3ihhy&quot;]/div[@id=&quot;cx1_agent_root&quot;]/div[@class=&quot;MuiBox-root css-19ku4tl&quot;]/div[@class=&quot;MuiGrid-root css-rfnosa&quot;]/div[@class=&quot;MuiBox-root css-j5cgbc&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root css-kk6lfv&quot;]/div[@class=&quot;MuiBox-root css-14zwn2r&quot;]/div[@class=&quot;MuiBox-root css-aftfqx&quot;]/button[@class=&quot;MuiBox-root css-1b77cue&quot;]/span[@class=&quot;dialKeyText MuiBox-root css-t1f1ul&quot;]</value>
      <webElementGuid>f60def50-6021-48d0-9716-5b931150c558</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[3]/div/div/div/div[3]/button[2]/span[2]</value>
      <webElementGuid>668fe251-54bd-41f2-a06f-16a132297f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='​'])[1]/following::span[3]</value>
      <webElementGuid>35b0631c-4ca5-47b9-ba4d-4b2be5ec06f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Close'])[1]/following::span[4]</value>
      <webElementGuid>ff7de375-79a1-48a0-931c-bed51206050e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='def'])[1]/preceding::span[2]</value>
      <webElementGuid>7e8f5d59-9d8f-411c-abf1-4bbd002a72b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ghi'])[1]/preceding::span[4]</value>
      <webElementGuid>94d8c4be-25da-4759-937e-4ed5aa28f314</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='abc']/parent::*</value>
      <webElementGuid>a884a7e9-a9e4-48d4-8a94-b95a5ffe8191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[2]/span[2]</value>
      <webElementGuid>dee09273-fbef-4bb8-8d65-bc3c9b23c130</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'abc' or . = 'abc')]</value>
      <webElementGuid>737cba1d-e5b8-4316-a034-378f82053a56</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
