<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__searchField</name>
   <tag></tag>
   <elementGuidId>92c69608-1422-47df-a4d2-2540633b7997</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#searchField</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='searchField']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;search-directory&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9727ee7e-419b-4559-afe9-0bb24b29761e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ba46918a-63fc-43f5-be31-2c11212c8fdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>e6544c18-4ab5-4c13-9ad6-45cda650f209</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>searchField</value>
      <webElementGuid>dcba3af3-13b9-4415-a2ca-8236d4d80ba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search for people, skills, teams, etc.</value>
      <webElementGuid>b9bd0ed4-91ae-471e-b852-a74e37d7ef38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fedd3594-b4a2-4ebc-a9bd-e8a5d938429a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>search-directory</value>
      <webElementGuid>c2241057-9a99-4a0c-a4a7-a11e53a8a38d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiInputBase-input MuiOutlinedInput-input MuiInputBase-inputSizeSmall MuiInputBase-inputAdornedStart css-162edyi</value>
      <webElementGuid>e41e8c74-32d4-4f07-b56f-0e3a4d522c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;searchField&quot;)</value>
      <webElementGuid>13ed4d32-25b4-438f-87e5-7171e072daa5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='searchField']</value>
      <webElementGuid>bd0e3036-bb81-4e94-8b7a-2ef772aaf06f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div[3]/div/div/section/div[2]/div[2]/div/div/input</value>
      <webElementGuid>e06d5666-8a8b-4ccd-85dc-4da76c9b940e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>da80b572-c5cd-499f-a999-243f80fe8c1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'searchField' and @placeholder = 'Search for people, skills, teams, etc.' and @type = 'text']</value>
      <webElementGuid>4ffc5c05-ae0b-4dff-a4b2-7e30601bdd3c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
