<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Outboundcalls_US</name>
   <tag></tag>
   <elementGuidId>b8398012-e9a1-4283-bf7a-2c6b48a0b6c2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>p.MuiTypography-root.MuiTypography-inherit.css-1352336</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div/section/div/div[3]/div/div/div/div/div/div[2]/div/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>[data-testid=&quot;interaction-08ab2982-b419-41a5-b70b-8e6ed9684bc7&quot;] >> internal:text=&quot;Outboundcalls_US&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>69f5249f-591c-45a1-9000-9713a888d1f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-inherit css-1352336</value>
      <webElementGuid>e3685483-f07f-48b1-b32d-8523d26d8fda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Outboundcalls_US</value>
      <webElementGuid>87951fd0-aaf0-4048-8783-b013214b4273</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@id=&quot;cx1_agent_root&quot;]/main[1]/div[@class=&quot;MuiBox-root css-1uq669f&quot;]/main[@class=&quot;MuiBox-root css-o3ihhy&quot;]/div[@id=&quot;cx1_agent_root&quot;]/div[@class=&quot;MuiBox-root css-19ku4tl&quot;]/div[@class=&quot;MuiBox-root css-13dfkjh&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container css-6sv6c4&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item css-1wxaqej&quot;]/section[@class=&quot;MuiBox-root css-19yj1du&quot;]/div[@class=&quot;MuiBox-root css-11x5kh1&quot;]/div[@class=&quot;noArrow
            false MuiBox-root css-1c8f6qt&quot;]/div[@class=&quot;interaction MuiBox-root css-0&quot;]/div[@class=&quot;MuiPaper-root MuiPaper-elevation MuiPaper-rounded MuiPaper-elevation1 MuiCard-root ccf-interaction css-1dgr6ct&quot;]/div[@class=&quot;MuiBox-root css-2yplm6&quot;]/div[@class=&quot;MuiBox-root css-7l26r7&quot;]/div[@class=&quot;css-ofo63b&quot;]/div[@class=&quot;MuiBox-root css-1xhj18k&quot;]/div[@class=&quot;MuiBox-root css-179ws4o&quot;]/p[@class=&quot;MuiTypography-root MuiTypography-inherit css-1352336&quot;]</value>
      <webElementGuid>1d3973a9-ca57-4f1f-a159-40ae295efe8d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cx1_agent_root']/div[2]/div[2]/div/div/section/div/div[3]/div/div/div/div/div/div[2]/div/p</value>
      <webElementGuid>e51387b5-3317-4b46-8f50-657b3507eaeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Dialed number is invalid'])[1]/following::p[2]</value>
      <webElementGuid>8be07f85-ab80-41a8-8210-571888e0d41d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Outboundcalls_US']/parent::*</value>
      <webElementGuid>efd52594-9977-4f27-bf15-88b616b20f97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/p</value>
      <webElementGuid>c7609a7a-a6b4-44ee-b592-7c94d03bc417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Outboundcalls_US' or . = 'Outboundcalls_US')]</value>
      <webElementGuid>0bbca9d4-69b8-4d57-b4b0-017becb77cea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
